version: "3"

services:
  db:
    container_name: db-container
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgresVolume:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"


  api:
    container_name: api-container
    build: .
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - db
    restart: unless-stopped


volumes:
  postgresVolume:

