services:
  db:
    container_name: db-container
    image: 'postgres:latest'
    volumes:
      - postgresVolume:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always


  api:
    container_name: api-container
    build: .
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      db:
        condition: service_healthy
    restart: always


volumes:
  postgresVolume:

